### ISSUE TITLE
Add pull and issue templates

### ISSUE THREAD

**Issue by Aayush-hub** [Developer-Student-Clubs-VSSUT-Burla/CamOps#11]
Add pull request and issue template which provides reference to contributors and make contributions attractive.

**Comment by Aayush-hub** [comment]
@Rittik-Biswal2000 Can I look into it?

**Comment by Rittik-Biswal2000** [comment]
Please check your readme pr . i think cd book-recommendation-........  isn't correct

**Comment by Aayush-hub** [comment]
@Rittik-Biswal2000 Yes, sorry for that, I will correct it in my next PR.

**Comment by Aayush-hub** [comment]
@Rittik-Biswal2000 I have updated the Readme and made PR. Now can I work on this issue?

**Comment by Rittik-Biswal2000** [comment]
Yes
