### ISSUE TITLE
Incorrect commands in README.md

### ISSUE THREAD

**Issue by madhuvanthi27** [Developer-Student-Clubs-VSSUT-Burla/CamOps#16]
Hey,

After forking the project, the command for navigating to this project directory is
`cd CamOps` 
but **How to Contribute** section in the README.md says
`cd Book-Recommendation-Analysis`
which will give an error of 'no such file or directory'

![gssoc-1](https://user-images.githubusercontent.com/68513622/111742875-d25e1400-88ae-11eb-97e4-cdccd1d39f27.jpeg)

Also, the clone link is 
`git clone https://github.com/<your_user_name>/CamOps.git`
the guidelines in README.md say
`git clone https://github.com/<your_user_name>/Developer-Student-Clubs-VSSUT-Burla/CamOps.git`
this command will give the error of 'too many arguments'.

![gssoc-2](https://user-images.githubusercontent.com/68513622/111745033-17377a00-88b2-11eb-9deb-a03aa8a64550.jpeg)

I would love to work on this issue under GSSOC'21 :)

**Comment by Rittik-Biswal2000** [comment]
This issue is already resolved
